### ISSUE TITLE
大佬，我想问下，你about页面，那个Terminal  界面是怎么搞出来的?

### ISSUE THREAD

**Issue by Huhui-coder** [xrkffgg/xrkffgg.github.io#1]
大佬，我想问下，你about页面，那个Terminal  界面是怎么搞出来的?

**Comment by xrkffgg** [comment]
@Huhui-coder 不好意思 刚看到 是仿照着这个 https://github.com/dongsuo/vue-terminal

你可以在我的项目里看是怎么使用的， https://github.com/xrkffgg/Kvue
